### ISSUE TITLE
Script can't running

### ISSUE THREAD

**Issue by akrhin** [Tes3awy/Cisco-Configuration-Using-Python-Jinja-CSV#2]
I tried to use your generator, but even on test your test-csv there was an error. What is the reason?
```
 python3 cisco_config_generator.py
Traceback (most recent call last):
  File "cisco_config_generator.py", line 30, in <module>
    from cisco_validation import validate_cisco_config
  File "/git/Cisco-Configuration-Using-Python-Jinja-CSV/cisco_validation.py", line 250, in <module>
    def validate_cisco_config() -> list[bool, dict]:
TypeError: 'type' object is not subscriptable
```

**Comment by akrhin** [comment]
python version....
